apiVersion: apps/v1
kind: Deployment
metadata:
  name: koru-email
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: koru-email
  template:
    metadata:
      labels:
        app: koru-email
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: koru-email
          image: "ghcr.io/jamdon2/koru-email:sha-1c0c890"
          ports:
            - containerPort: 8000
          env:
            - name: RESEND_API_KEY
              valueFrom:
                secretKeyRef:
                  name: koru-email-secret
                  key: RESEND_API_KEY
            - name: RESEND_AUDIENCE_ID
              valueFrom:
                secretKeyRef:
                  name: koru-email-secret
                  key: RESEND_AUDIENCE_ID
            - name: EMAIL_FROM
              value: "Koru <hello@koru.cash>"
            - name: RABBITMQ_HOST
              value: rabbitmq.rabbitmq.svc.cluster.local
            - name: RABBITMQ_USER
              value: user
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: koru-email-secret
                  key: RABBITMQ_PASSWORD
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
