apiVersion: apps/v1
kind: Deployment
metadata:
  name: koru-api-worker
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: koru-api-worker
  template:
    metadata:
      labels:
        app: koru-api-worker
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: koru-api-worker
          image: "ghcr.io/jamdon2/koru-api:sha-7a209aa"
          command: ["celery"]
          args: ["-A", "api.core.celery", "worker", "--loglevel=info", "-P", "gevent"]
          env:
            - name: APP_URL
              value: https://koru.cash
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: koru-api-secret
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: koru-api-secret
                  key: JWT_SECRET
            - name: REDIS_HOST
              value: redis-master.database-services.svc.cluster.local
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: koru-api-secret
                  key: REDIS_PASSWORD
            - name: RABBITMQ_HOST
              value: rabbitmq.rabbitmq.svc.cluster.local
            - name: RABBITMQ_USER
              value: user
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: koru-api-secret
                  key: RABBITMQ_PASSWORD
            - name: HCAPTCHA_SITEKEY
              value: "e8140486-54b8-48da-9ec0-58aa1b868c0c"
            - name: HCAPTCHA_SECRET
              valueFrom:
                secretKeyRef:
                  name: koru-api-secret
                  key: HCAPTCHA_SECRET
            - name: GOCARDLESS_SECRET_ID
              valueFrom:
                secretKeyRef:
                  name: koru-api-secret
                  key: GOCARDLESS_SECRET_ID
            - name: GOCARDLESS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: koru-api-secret
                  key: GOCARDLESS_SECRET_KEY
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "1"
