apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: cloudflare-mtls-tlsoption
  namespace: default
spec:
  clientAuth:
    secretNames:
      - cloudflare-mtls-ca-secret
    clientAuthType: RequireAndVerifyClientCert
