apiVersion: apps/v1
kind: Deployment
metadata:
  name: koru-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: koru-api
  template:
    metadata:
      labels:
        app: koru-api
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: koru-api
          image: "ghcr.io/jamdon2/koru-api:sha-01c2be7"
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: koru-api-secret
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: koru-api-secret
                  key: JWT_SECRET
            - name: REDIS_HOST
              value: redis-master.database-services.svc.cluster.local
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: koru-api-secret
                  key: REDIS_PASSWORD
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "2Gi"
              cpu: "2"
