deploymentMode: SingleBinary
loki:
  storage:
    type: filesystem
  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h
singleBinary:
  replicas: 1
  persistence:
    storageClass: longhorn
read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0
