deploymentMode: SingleBinary
loki:
  storage:
    type: filesystem
singleBinary:
  replicas: 1
  persistence:
    storageClass: longhorn
read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0
