deploymentMode: SingleBinary
loki:
  storage:
    type: filesystem
  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h
  ui:
    enabled: true
singleBinary:
  replicas: 1
  persistence:
    storageClass: longhorn
read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0
gateway:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd,monitoring-prometheus-basic-auth-middleware@kubernetescrd
    hosts:
      - host: loki.koru.cash
        paths:
          - path: /
    tls:
      - secretName: loki-tls
        hosts:
          - loki.koru.cash
monitoring:
  dashboards:
    enabled: true
  serviceMonitor:
    enabled: true
