architecture: standalone

auth:
  existingPasswordSecret: "rabbitmq-auth"
  existingErlangSecret: "rabbitmq-auth"
persistence:
  enabled: true
  storageClass: "longhorn-crypto"
  size: 5Gi
ingress:
  enabled: true
  pathType: Prefix
  hostname: rabbitmq.koru.cash
  tls: true
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
metrics:
  enabled: true
  serviceMonitor:
    default:
      enabled: true
  prometheusRule:
    enabled: true
